/// ═══════════════════════════════════════════════════════════════
/// AUTO-GENERATED by BotForge — DO NOT EDIT MANUALLY
/// Organisation: AutoDeals Sales Assistant (b84e8981-d5a3-4df2-b57d-d895f4002c7e)
/// Generated: 2026-05-01T01:17:36.268Z
/// Chatbot ID: 48103454-ab25-496e-a555-b4fcd0c62e13
/// API Key: 
/// ═══════════════════════════════════════════════════════════════
library;

class AppConfig {
  AppConfig._();

  // ── Brand Identity ──────────────────────────────────────────────
  static const String businessName   = 'AutoDeals Sales Assistant';
  static const String tagline        = '';
  static const String botName        = 'AutoDeals Sales Assistant';
  static const String botRole        = 'Customer Experience Assistant';
  static const String welcomeMessage = 'Hi there! 👋 I\'m **AutoDeals Sales Assistant**, your personal assistant at **AutoDeals Sales Assistant**. How can I help you today?';

  static const List<String> quickReplies = [
    '💰 Pricing & Plans',
    '🛠️ Our Services',
    '📞 Contact Support'
  ];

  // ── Visuals ──────────────────────────────────────────────────────
  static const String primaryColorHex = '#e85518';
  static const String accentColorHex  = '#0f172a';
  static const String botAvatarAsset  = 'assets/images/bot_avatar.png';
  static const String logoAsset       = 'assets/images/logo.png';

  // ── Backend ──────────────────────────────────────────────────────
  static const String apiBaseUrl     = 'https://api.botforge.app';
  static const String chatEndpoint   = '/chatbots/mobile/:chatbotId';
  static const String organisationId = 'b84e8981-d5a3-4df2-b57d-d895f4002c7e';
  static const String chatbotId = '48103454-ab25-496e-a555-b4fcd0c62e13';
  static const String apiKey = '';

  // ── Chat Session ────────────────────────────────────────────────
  static const String chatId = '';  // Generated on first chat

  // ── Business Hours ───────────────────────────────────────────────
  static const bool   showBusinessHours = false;
  static const String businessHours     = '';
  static const String offlineMessage    =
      'We are currently outside business hours. I will still do my best to help, '
      'but a human agent will follow up. 🌙';

  // ── Social / Contact ─────────────────────────────────────────────
  static const String whatsappNumber  = '';
  static const String telegramHandle  = '';
  static const String supportEmail    = '';
  static const String websiteUrl      = '';

  // ── Feature Flags ─────────────────────────────────────────────────
  static const bool enableFileAttachments = true;
  static const bool enableVoiceMessages   = false;
  static const bool enableRatings         = true;
  static const bool enableTypingIndicator = true;
  static const bool enableReadReceipts    = true;
}